apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
    team: mongodb-team
    org: apple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      team: gcsdba-hadoop
  template:
    metadata:
      labels:
        app: mongodb
        team: gcsdba-hadoop
    spec:
      containers:
      - name: mongodb
        image: mongo 
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              namee: mongodb-secret
              key: mongo-root-password 